# Generated by Django 3.2.4 on 2021-12-04 19:32

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=50)),
                ('zona', models.CharField(choices=[('1', 'Zona 1'), ('2', 'Zona 2'), ('3', 'Zona 3'), ('5', 'Zona 5')], default='1', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Trimestre1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Trimestre2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Trimestre3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Trimestre4',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Trimestre5',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Trimestre6',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('jefe_ficha', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('jornada_de_ficha', models.CharField(choices=[('M', 'mañana'), ('T', 'tarde')], default='M', max_length=10)),
                ('trimestre_actual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_instructor', models.BooleanField(default=False, verbose_name='Es instructor')),
                ('is_coordinador', models.BooleanField(default=False, verbose_name='Es coordinador')),
                ('is_JGrupo', models.BooleanField(default=False, verbose_name='Es jefe de grupo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre6',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Competencia_Trimestre6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.competencia_trimestre6')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre5',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Competencia_Trimestre5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.competencia_trimestre5')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre4',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Competencia_Trimestre4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.competencia_trimestre4')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Competencia_Trimestre3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.competencia_trimestre3')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Competencia_Trimestre2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.competencia_trimestre2')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Competencia_Trimestre1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.competencia_trimestre1')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_instructor', models.CharField(choices=[('TE', 'Tecnico'), ('TR', 'Transversal'), ('BI', 'Bilinguismo')], default='TE', max_length=3)),
                ('fichas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
    ]
