# Generated by Django 3.2.4 on 2021-12-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=50)),
                ('zona', models.CharField(choices=[('1', 'Zona 1'), ('2', 'Zona 2'), ('3', 'Zona 3'), ('5', 'Zona 5')], default='1', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('jefe_ficha', models.CharField(max_length=50)),
                ('jornada_de_ficha', models.CharField(choices=[('M', 'mañana'), ('T', 'tarde')], default='M', max_length=10)),
                ('trimestre_actual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('actividad', models.CharField(max_length=1500)),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('actividad', models.CharField(max_length=1500)),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('actividad', models.CharField(max_length=1500)),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre4',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('actividad', models.CharField(max_length=1500)),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre5',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('actividad', models.CharField(max_length=1500)),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre6',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('actividad', models.CharField(max_length=1500)),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('resultado_competencia', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_instructor', models.CharField(choices=[('TE', 'Tecnico'), ('TR', 'Transversal'), ('BI', 'Bilinguismo')], default='TE', max_length=3)),
                ('ambiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes')),
                ('fichas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas')),
            ],
        ),
    ]
