# Generated by Django 3.2.4 on 2021-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0002_alter_competencia_trimestre1_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia_trimestre2',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competencia_trimestre3',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competencia_trimestre4',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competencia_trimestre5',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competencia_trimestre6',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
