# Generated by Django 3.2.5 on 2021-12-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0002_delete_filtros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtros',
            fields=[
                ('id_resultado', models.IntegerField()),
                ('nombre_resultado', models.CharField(max_length=1500)),
                ('actividad_id', models.IntegerField()),
                ('competencia_id', models.IntegerField()),
                ('trimestres_id', models.BigIntegerField()),
                ('id_competencia', models.IntegerField()),
                ('nombre_competencia', models.CharField(max_length=1500)),
                ('codigo', models.IntegerField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('trimestres', models.CharField(max_length=3)),
                ('id_actividad', models.IntegerField()),
                ('nombre_actividad', models.CharField(max_length=1500)),
            ],
            options={
                'db_table': 'filtros',
                'managed': False,
            },
        ),
    ]
