# Generated by Django 3.2.4 on 2021-12-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0003_auto_20211213_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='fichas',
        ),
    ]
