# Generated by Django 3.2.4 on 2021-12-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0004_remove_instructor_fichas'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimestre1',
            name='ambiente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trimestre2',
            name='ambiente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trimestre3',
            name='ambiente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trimestre4',
            name='ambiente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trimestre5',
            name='ambiente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trimestre6',
            name='ambiente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
            preserve_default=False,
        ),
    ]
