# Generated by Django 3.2.4 on 2021-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0005_auto_20211213_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas',
            name='programa_de_formacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='programa_de_formacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
