# Generated by Django 3.2.4 on 2021-12-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0006_auto_20211213_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='programa_de_formacion',
            field=models.CharField(choices=[('ADSI', 'Analisis y desarrollo de sistemas de informacion')], default='ADSI', max_length=10),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='programa_de_formacion',
            field=models.CharField(choices=[('ADSI', 'Analisis y desarrollo de sistemas de informacion')], default='ADSI', max_length=10),
        ),
    ]
