# Generated by Django 3.2.4 on 2021-12-13 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0007_auto_20211213_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre1',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas'),
        ),
        migrations.AlterField(
            model_name='trimestre2',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas'),
        ),
        migrations.AlterField(
            model_name='trimestre3',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas'),
        ),
        migrations.AlterField(
            model_name='trimestre4',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas'),
        ),
        migrations.AlterField(
            model_name='trimestre5',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas'),
        ),
        migrations.AlterField(
            model_name='trimestre6',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.fichas'),
        ),
    ]
