# Generated by Django 3.2.4 on 2021-12-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0008_auto_20211213_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre1',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
        ),
        migrations.AlterField(
            model_name='trimestre2',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
        ),
        migrations.AlterField(
            model_name='trimestre3',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
        ),
        migrations.AlterField(
            model_name='trimestre4',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
        ),
        migrations.AlterField(
            model_name='trimestre5',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
        ),
        migrations.AlterField(
            model_name='trimestre6',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
        ),
    ]
