# Generated by Django 3.2.4 on 2021-12-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0009_auto_20211213_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trimestre1',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='trimestre2',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='trimestre3',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='trimestre4',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='trimestre5',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='trimestre6',
            name='ambiente',
        ),
        migrations.AddField(
            model_name='fichas',
            name='ambiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apphorarios.ambientes'),
            preserve_default=False,
        ),
    ]
