# Generated by Django 3.2.4 on 2021-12-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apphorarios', '0010_auto_20211213_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='zona',
            field=models.CharField(choices=[('Zona 1', '1'), ('Zona 2', '2'), ('Zona 3', '3'), ('Zona 5', '5')], default='Zona 1', max_length=10),
        ),
    ]
